version: '3.1'

services:
  postgres:
    container_name: postgres_korona_container
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"

  korona-api:
    container_name: korona
    image: damintsew/korona-api
    ports:
      - "3333:6666"
#  bot:
#    container_name: korona-watcher-bot
#    image: damintsew/korona-watcher-bot
#    environment:
#      DB_HOST: postgres
#      TG_TOKEN: "xxx"

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin4_container
#    restart: always
#    ports:
#      - "5050:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: das@das.com
#      PGADMIN_DEFAULT_PASSWORD: admin
